name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java-version:
            - '21'
            - '17'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
          cache-dependency-path: | # optional
            build.sbt
            project/build.properties
      - name: Build with SBT
        run: sbt clean test package

