name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
        matrix:
          settings:
            - spark:
              - '3.5.6'
              - '3.4.2'
              scala:
              - '2.13.16'
              - '2.12.20'
              java: '8'
            - spark:
                - '4.0.0'
#                - '4.1.0-preview1'
              scala: '2.13.16'
              java:
               - '17'
               - '21'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.settings.java }}
          cache: 'sbt'
          cache-dependency-path: | # optional
            build.sbt
            project/build.properties
      - name: Install SBT
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https curl gnupg -yqq
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
          sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
          sudo apt-get update
          sudo apt-get install sbt
      - name: Build with SBT
        run: sbt clean test package -Dscala.version=${{ matrix.settings.scala }} -Dspark.version=${{ matrix.settings.spark }}

